#!/usr/bin/env bash

set -euo pipefail

declare -r PACT_DOCKER_IMAGE="tapendium/pact-cli:latest"

plugin_dir="$(dirname "$(dirname "${BASH_SOURCE[0]}")")"

env_file="$(
	cat <<-EOF
		BUILDKITE_BRANCH
		BUILDKITE_BUILD_URL
		BUILDKITE_COMMIT
		BUILDKITE_GRAPHQL_API_TOKEN
		BUILDKITE_PIPELINE_NAME
		BUILDKITE_PLUGIN_PACT_CLI_ACTION
		BUILDKITE_PLUGIN_PACT_CLI_DEBUG
		BUILDKITE_PLUGIN_PACT_CLI_GRAPHQL_URL
		BUILDKITE_PLUGIN_PACT_CLI_PACTICIPANT
		BUILDKITE_PLUGIN_PACT_CLI_SKIP_PUBLISH
		BUILDKITE_REPO
		PACT_BROKER_BASE_URL
		PACT_BROKER_PASSWORD
		PACT_BROKER_USERNAME
		BUILDKITE_JOB_ID
		BUILDKITE_BUILD_ID
		BUILDKITE_ACCESS_TOKEN
	EOF
)"

docker run \
	--workdir /workdir \
	--volume "$plugin_dir":/workdir/plugin:ro \
	--volume "$PWD":/workdir \
	--volume "$(command -v buildkite-agent)":/usr/bin/buildkite-agent \
	--env-file <(echo "$env_file") \
	"$PACT_DOCKER_IMAGE" \
	plugin/lib/run.sh
